### ISSUE TITLE
[FEATURE] map and current power-up in display

### ISSUE THREAD

**Issue by notjedi** [philkr/pystk#34]
feature request - display minimap and power-up just like SuperTuxKart.

**Comment by jedi2610** [comment]
the player currently doesn't know what the current power-up is as it's not displayed on the screen. i'm trying to train an agent here and feed the raw pixels as input to the neural network. although this project is more likely to be used as an env for training agents and not for actually playing, when i try to make the agent play on the actual `SuperTuxKart`, this would clearly fail(because i can't get the active power-up without a custom build of the `SuperTuxKart`).
